# Generated by Django 5.1.15 on 2026-07-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0002_billdetail_vat_amount_billdetail_vat_base_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETaxConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ชื่อผู้ขาย"
                    ),
                ),
                (
                    "seller_tax_id",
                    models.CharField(
                        blank=True, max_length=13, verbose_name="เลขผู้เสียภาษี 13 หลัก"
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        default="00000", max_length=5, verbose_name="รหัสสาขา"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="ที่อยู่")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("service_provider", "ผ่าน Service Provider"),
                            ("direct", "เชื่อมตรงกับสรรพากร"),
                        ],
                        default="service_provider",
                        max_length=20,
                        verbose_name="ช่องทางยื่น",
                    ),
                ),
                (
                    "cert_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="หมายเหตุใบรับรอง (CA)"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="เปิดใช้งาน"),
                ),
            ],
            options={
                "verbose_name": "ตั้งค่า e-Tax",
                "verbose_name_plural": "ตั้งค่า e-Tax",
            },
        ),
        migrations.CreateModel(
            name="ETaxDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        default="T02", max_length=20, verbose_name="ประเภทเอกสาร"
                    ),
                ),
                ("xml", models.TextField(blank=True, verbose_name="XML")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร่าง"),
                            ("signed", "ลงลายเซ็นแล้ว"),
                            ("submitted", "ส่งแล้ว"),
                            ("accepted", "สรรพากรรับแล้ว"),
                            ("failed", "ล้มเหลว"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "rd_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="เลขอ้างอิงสรรพากร"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etax",
                        to="sales.billhead",
                        verbose_name="บิล",
                    ),
                ),
            ],
            options={
                "verbose_name": "เอกสาร e-Tax",
                "verbose_name_plural": "เอกสาร e-Tax",
            },
        ),
    ]
