# Generated by Django 5.1.15 on 2026-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="รหัสฟังก์ชัน")),
                ("name_th", models.CharField(max_length=100, verbose_name="ชื่อเมนู")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("transaction", "ธุรกรรม"),
                            ("report", "รายงาน"),
                            ("data", "ข้อมูล"),
                            ("setting", "ตั้งค่า"),
                        ],
                        default="transaction",
                        max_length=20,
                        verbose_name="กลุ่ม",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=20, verbose_name="ไอคอน"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ลำดับ")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="คำอธิบาย"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขล่าสุด"),
                ),
            ],
            options={
                "verbose_name": "เมนู/ฟังก์ชัน (เปิด-ปิด)",
                "verbose_name_plural": "เมนู/ฟังก์ชัน (เปิด-ปิด)",
                "ordering": ["group", "order"],
            },
        ),
    ]
