# Generated by Django 5.1.15 on 2026-07-19 12:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="ชื่อแหล่งการเงิน"),
                ),
                (
                    "is_cash",
                    models.BooleanField(default=False, verbose_name="เป็นเงินสด"),
                ),
            ],
            options={
                "verbose_name": "บัญชีการเงิน",
                "verbose_name_plural": "บัญชีการเงิน",
            },
        ),
        migrations.CreateModel(
            name="FinanceLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่")),
                (
                    "ref_no",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="เลขที่รายการ"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="รายการ"),
                ),
                (
                    "amount_in",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="เงินเข้า",
                    ),
                ),
                (
                    "amount_out",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="เงินออก",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="ค่าธรรมเนียม",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="finance.bankaccount",
                        verbose_name="แหล่งการเงิน",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้บันทึก",
                    ),
                ),
            ],
            options={
                "verbose_name": "สมุดบัญชีการเงิน",
                "verbose_name_plural": "สมุดบัญชีการเงิน",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
