# Generated by Django 5.1.15 on 2026-07-19 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "เข้าดู"),
                            ("create", "สร้าง"),
                            ("update", "แก้ไข"),
                            ("delete", "ลบ"),
                            ("print", "พิมพ์"),
                            ("login", "เข้าสู่ระบบ"),
                        ],
                        max_length=10,
                        verbose_name="การกระทำ",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=100, verbose_name="โมเดล"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="รหัสอ้างอิง"
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="รายละเอียด")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลา"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "บันทึกการตรวจสอบ (Audit Log)",
                "verbose_name_plural": "บันทึกการตรวจสอบ (Audit Log)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "เจ้าของร้าน"),
                            ("manager", "ผู้จัดการ"),
                            ("sales", "พนักงานขาย"),
                            ("account", "บัญชี"),
                        ],
                        default="sales",
                        max_length=20,
                        verbose_name="บทบาท",
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="เบอร์โทร"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "โปรไฟล์ผู้ใช้ (บทบาท)",
                "verbose_name_plural": "โปรไฟล์ผู้ใช้ (บทบาท)",
            },
        ),
    ]
