# Generated by Django 5.1.15 on 2026-07-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่")),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "เข้า"), ("out", "ออก")],
                        max_length=3,
                        verbose_name="ทิศทาง",
                    ),
                ),
                (
                    "weight_gram",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="น้ำหนัก (กรัม)"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="หมายเหตุ"
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.metaltype",
                        verbose_name="ประเภทโลหะ",
                    ),
                ),
            ],
            options={
                "verbose_name": "การเคลื่อนไหวสต็อก",
                "verbose_name_plural": "การเคลื่อนไหวสต็อก",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
