# Generated by Django 5.1.15 on 2026-07-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_supplier_vatsetting_metaltype_vat_exempt_and_more"),
        ("inventory", "0001_initial"),
        ("sales", "0002_billdetail_vat_amount_billdetail_vat_base_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_date", models.DateField(verbose_name="วันที่รับเข้า")),
                (
                    "weight_gram",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="น้ำหนักรับเข้า (กรัม)",
                    ),
                ),
                (
                    "remaining_gram",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="คงเหลือ (กรัม)"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ต้นทุนต่อกรัม"
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="catalog.metaltype",
                        verbose_name="ประเภทโลหะ",
                    ),
                ),
                (
                    "source_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produced_lots",
                        to="sales.billdetail",
                        verbose_name="รายการรับซื้อต้นทาง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ล็อตต้นทุน (FIFO)",
                "verbose_name_plural": "ล็อตต้นทุน (FIFO)",
                "ordering": ["received_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="LotConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_gram",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="น้ำหนักที่ตัด (กรัม)",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="ต้นทุนส่วนนี้"
                    ),
                ),
                (
                    "sale_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_consumptions",
                        to="sales.billdetail",
                        verbose_name="รายการขาย",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumptions",
                        to="inventory.stocklot",
                        verbose_name="ล็อตต้นทุน",
                    ),
                ),
            ],
            options={
                "verbose_name": "การตัดล็อตต้นทุน",
                "verbose_name_plural": "การตัดล็อตต้นทุน",
            },
        ),
    ]
