"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(key, default=False):
    return os.environ.get(key, str(default)).strip().lower() in ("1", "true", "yes", "on")


def _env_list(key, default=""):
    return [x.strip() for x in os.environ.get(key, default).split(",") if x.strip()]


# ---------------------------------------------------------------------------
# ค่าที่อ่านจาก environment (production ตั้งผ่าน .env / docker-compose)
# ค่า default = โหมด dev (ใช้ SQLite ได้ทันที) — ห้ามใช้ค่า default บน production
# ---------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-s5onfuh6%f@d(pkgenmaat1u-2@092o#l#sr4oi1lb21t)ie%(")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

# production: ตั้ง DJANGO_ALLOWED_HOSTS="ong.example.com,www.ong.example.com"
ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "*") if not DEBUG else ["*"]

# หลัง reverse proxy (nginx) ที่ทำ HTTPS ให้ระบุโดเมนที่เชื่อถือสำหรับ CSRF
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    # project apps
    "core",
    "accounts",
    "customers",
    "catalog",
    "pricing",
    "sales",
    "consignment",
    "inventory",
    "finance",
    "reports",
    "notifications",
    "etax",
]

# ตั้งค่าท้องถิ่นไทย
LANGUAGE_CODE = "th"
TIME_ZONE = "Asia/Bangkok"
USE_TZ = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # เสิร์ฟ static ใน production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_context",   # เมนู + บริษัท + ราคาทอง
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Auth
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# Media (รูปบัตร/ชิ้นงาน)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Static (vendor HTMX offline)
STATICFILES_DIRS = [BASE_DIR / "static"]

# REST framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ลำดับความสำคัญของการเลือกฐานข้อมูล:
#   1) DATABASE_URL (Railway/Render/Heroku ใส่มาให้อัตโนมัติ)
#   2) POSTGRES_DB + ตัวแปรแยก (docker-compose ที่เราทำเอง)
#   3) SQLite (dev)
_CONN_MAX_AGE = int(os.environ.get("DB_CONN_MAX_AGE", "60"))


def _databases_from_url(url):
    """แปลง postgres URL → Django DATABASES (ไม่พึ่ง lib ภายนอก)"""
    from urllib.parse import urlparse, unquote
    u = urlparse(url)
    return {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (u.path or "/").lstrip("/"),
            "USER": unquote(u.username or ""),
            "PASSWORD": unquote(u.password or ""),
            "HOST": u.hostname or "",
            "PORT": str(u.port or "5432"),
            "CONN_MAX_AGE": _CONN_MAX_AGE,
        }
    }


_DB_URL = os.environ.get("DATABASE_URL", "").strip()
if _DB_URL.startswith(("postgres://", "postgresql://")):
    DATABASES = _databases_from_url(_DB_URL)
elif os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ.get("POSTGRES_USER", "ong"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": _CONN_MAX_AGE,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization (ไทย)
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "th"

TIME_ZONE = "Asia/Bangkok"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"   # collectstatic ปลายทาง (WhiteNoise/nginx เสิร์ฟ)

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
        if not DEBUG else "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Security (มีผลเฉพาะ production, DEBUG=False) — ทำงานหลัง reverse proxy HTTPS
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "0"))  # เปิดเมื่อ HTTPS นิ่งแล้ว
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = "DENY"
    # ให้ Django redirect เป็น https ได้ถ้าต้องการ (nginx ทำ redirect อยู่แล้ว โดย default ปิดไว้)
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
