# Generated by Django 5.1.15 on 2026-07-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="เลขบัตรประชาชน"
                    ),
                ),
                (
                    "name_th",
                    models.CharField(max_length=150, verbose_name="ชื่อ-นามสกุล (ไทย)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="ชื่อ-นามสกุล (อังกฤษ)"
                    ),
                ),
                (
                    "birthday",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="วันเดือนปีเกิด"
                    ),
                ),
                (
                    "religion",
                    models.CharField(blank=True, max_length=40, verbose_name="ศาสนา"),
                ),
                ("address", models.TextField(verbose_name="ที่อยู่")),
                (
                    "card_issue_date",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="วันที่ออกบัตร"
                    ),
                ),
                (
                    "card_expire_date",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="วันที่บัตรหมดอายุ"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="เบอร์โทร"
                    ),
                ),
                ("is_vip", models.BooleanField(default=False, verbose_name="เป็น VIP")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขเมื่อ"),
                ),
            ],
            options={
                "verbose_name": "ลูกค้า",
                "verbose_name_plural": "ลูกค้า",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="ชื่อยศ"),
                ),
                (
                    "no_service_fee",
                    models.BooleanField(
                        default=False, verbose_name="ยกเว้นค่าบริการ (ไม่หัก%)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "ยศสมาชิก",
                "verbose_name_plural": "ยศสมาชิก",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CustomerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="customers/%Y/%m/", verbose_name="รูป"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("id_card", "รูปบัตรประชาชน"), ("other", "อื่น ๆ")],
                        default="id_card",
                        max_length=20,
                        verbose_name="ประเภทรูป",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="อัปโหลดเมื่อ"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="customers.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "รูปลูกค้า",
                "verbose_name_plural": "รูปลูกค้า",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="member_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="customers.memberrank",
                verbose_name="ยศสมาชิก",
            ),
        ),
    ]
