# Generated by Django 5.1.15 on 2026-07-19 12:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อบริษัท")),
                ("address", models.TextField(blank=True, verbose_name="ที่อยู่")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เลขผู้เสียภาษี"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="โทรศัพท์"
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="สาขา/สำนักงาน"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company/",
                        verbose_name="โลโก้",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลบริษัท",
                "verbose_name_plural": "ข้อมูลบริษัท",
            },
        ),
        migrations.CreateModel(
            name="Duration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months",
                    models.PositiveIntegerField(unique=True, verbose_name="จำนวนเดือน"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
            ],
            options={
                "verbose_name": "ระยะเวลาขายฝาก",
                "verbose_name_plural": "ระยะเวลาขายฝาก",
                "ordering": ["months"],
            },
        ),
        migrations.CreateModel(
            name="GoldPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="วันที่")),
                (
                    "bar_sell",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ทองแท่งขายออก"
                    ),
                ),
                (
                    "bar_buy",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ทองแท่งรับซื้อ"
                    ),
                ),
                (
                    "jewelry_buy",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="ทองรูปพรรณรับซื้อ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ราคาทองรายวัน",
                "verbose_name_plural": "ราคาทองรายวัน",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        unique=True,
                        verbose_name="อัตรา (%/เดือน)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
            ],
            options={
                "verbose_name": "อัตราดอกเบี้ยขายฝาก",
                "verbose_name_plural": "อัตราดอกเบี้ยขายฝาก",
                "ordering": ["-rate"],
            },
        ),
        migrations.CreateModel(
            name="MetalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="รหัส")),
                ("name_th", models.CharField(max_length=50, verbose_name="ชื่อไทย")),
                (
                    "formula",
                    models.CharField(
                        choices=[
                            ("gold", "สูตรทอง (×factor×% + หักค่าบริการ<90%)"),
                            ("flat", "ตั้งราคาเอง (×% ไม่หักค่าบริการ)"),
                        ],
                        default="gold",
                        max_length=10,
                        verbose_name="สูตรคำนวณ",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "ประเภทสินค้า (โลหะ)",
                "verbose_name_plural": "ประเภทสินค้า (โลหะ)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3"),
                        max_digits=4,
                        verbose_name="ค่าบริการ (%)",
                    ),
                ),
                (
                    "gold_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.0656"),
                        max_digits=8,
                        verbose_name="factor ทอง",
                    ),
                ),
                (
                    "fee_threshold_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("90"),
                        max_digits=5,
                        verbose_name="เกณฑ์%ทองที่เริ่มหัก",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
            ],
            options={
                "verbose_name": "ตั้งค่าค่าบริการ",
                "verbose_name_plural": "ตั้งค่าค่าบริการ",
            },
        ),
        migrations.CreateModel(
            name="MetalPriceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price_per_gram",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ราคาตั้งต่อกรัม"
                    ),
                ),
                (
                    "metal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_setting",
                        to="catalog.metaltype",
                        verbose_name="โลหะ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ราคาตั้งเอง (เงิน/แพลทตินั่ม)",
                "verbose_name_plural": "ราคาตั้งเอง (เงิน/แพลทตินั่ม)",
            },
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อสินค้า")),
                (
                    "diamond_profit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="%กำไรเพชร",
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.metaltype",
                        verbose_name="ประเภท",
                    ),
                ),
            ],
            options={
                "verbose_name": "เมนูสินค้า",
                "verbose_name_plural": "เมนูสินค้า",
            },
        ),
    ]
