# Generated by Django 5.1.15 on 2026-07-19 13:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อร้านส่ง")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เลขผู้เสียภาษี"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="โทรศัพท์"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="ที่อยู่")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
            ],
            options={
                "verbose_name": "ร้านส่ง / คู่ค้า",
                "verbose_name_plural": "ร้านส่ง / คู่ค้า",
            },
        ),
        migrations.CreateModel(
            name="VatSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("7"),
                        max_digits=5,
                        verbose_name="อัตรา VAT (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
            ],
            options={
                "verbose_name": "ตั้งค่า VAT",
                "verbose_name_plural": "ตั้งค่า VAT",
            },
        ),
        migrations.AddField(
            model_name="metaltype",
            name="vat_exempt",
            field=models.BooleanField(
                default=False,
                help_text="เช่น ทองคำแท่ง — ยกเว้น VAT; ทองรูปพรรณ = คิด VAT เฉพาะส่วนต่าง",
                verbose_name="ยกเว้น VAT ทั้งจำนวน",
            ),
        ),
        migrations.CreateModel(
            name="DocumentNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=6, verbose_name="รหัสนำหน้า")),
                (
                    "ym",
                    models.CharField(max_length=4, verbose_name="ปีเดือน (YYMM พ.ศ.)"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="เลขล่าสุด"),
                ),
            ],
            options={
                "verbose_name": "เลขที่เอกสาร (running)",
                "verbose_name_plural": "เลขที่เอกสาร (running)",
                "unique_together": {("prefix", "ym")},
            },
        ),
    ]
