# Generated by Django 5.1.15 on 2026-07-19 23:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_supplier_vatsetting_metaltype_vat_exempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaltype",
            name="apply_service_fee",
            field=models.BooleanField(
                default=True,
                help_text="โลหะนี้หักค่าบริการเมื่อ %<เกณฑ์ (ทอง=ใช่, เงิน/ทองคำขาว=ไม่)",
                verbose_name="หักค่าบริการ",
            ),
        ),
        migrations.AddField(
            model_name="metaltype",
            name="factor",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0.0656"),
                help_text="≈ 1/15.244",
                max_digits=8,
                verbose_name="factor (สำหรับสูตร gold)",
            ),
        ),
        migrations.AddField(
            model_name="metaltype",
            name="fee_threshold_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("90"),
                max_digits=5,
                verbose_name="เกณฑ์ % ที่เริ่มหักค่าบริการ",
            ),
        ),
        migrations.AddField(
            model_name="metaltype",
            name="price_source",
            field=models.CharField(
                choices=[
                    ("gold_bar", "อ้างอิงราคาทองแท่งรับซื้อ"),
                    ("manual", "ตั้งราคาเอง (MetalPriceSetting)"),
                ],
                default="gold_bar",
                max_length=10,
                verbose_name="แหล่งราคาตั้งต้น",
            ),
        ),
        migrations.AlterField(
            model_name="metaltype",
            name="formula",
            field=models.CharField(
                choices=[
                    ("gold", "สูตรทอง (×factor×% + หักค่าบริการ<90%)"),
                    ("flat", "ตั้งราคาเอง (×% ไม่หักค่าบริการ)"),
                ],
                default="gold",
                help_text="gold = base×factor×% (ทอง/นาก) · flat = base×% (เงิน/ทองคำขาว)",
                max_length=10,
                verbose_name="วิธีคำนวณ",
            ),
        ),
    ]
