# Generated by Django 5.1.15 on 2026-07-19 12:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsignmentContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_no",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="เลขที่สัญญา"
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่ทำสัญญา")),
                (
                    "weight_gram",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="น้ำหนัก (กรัม)"
                    ),
                ),
                (
                    "cost_assessment",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="ราคาประเมิน"
                    ),
                ),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="เงินต้นขายฝาก"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="วันครบกำหนด"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "อยู่ระหว่างสัญญา"),
                            ("redeemed", "ไถ่ถอนแล้ว"),
                            ("forfeited", "หลุดจำนำ"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="customers.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "duration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.duration",
                        verbose_name="ระยะเวลา",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.interestrate",
                        verbose_name="อัตราดอกเบี้ย",
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.metaltype",
                        verbose_name="ประเภทโลหะ",
                    ),
                ),
            ],
            options={
                "verbose_name": "สัญญาขายฝาก",
                "verbose_name_plural": "สัญญาขายฝาก",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Redeem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_no",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="เลขที่ใบไถ่ถอน"
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่ไถ่")),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="เงินต้น"
                    ),
                ),
                (
                    "interest_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="ดอกเบี้ยรับ",
                    ),
                ),
                (
                    "fee_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="ค่าธรรมเนียมรับ",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redeems",
                        to="consignment.consignmentcontract",
                        verbose_name="สัญญาขายฝาก",
                    ),
                ),
            ],
            options={
                "verbose_name": "การไถ่ออก",
                "verbose_name_plural": "การไถ่ออก",
            },
        ),
    ]
