# Generated by Django 5.1.15 on 2026-07-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_access_token",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Channel Access Token"
                    ),
                ),
                (
                    "channel_secret",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Channel Secret"
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=3, verbose_name="แจ้งเตือนล่วงหน้า (วัน)"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="เปิดใช้งาน"),
                ),
            ],
            options={
                "verbose_name": "ตั้งค่า LINE OA",
                "verbose_name_plural": "ตั้งค่า LINE OA",
            },
        ),
        migrations.CreateModel(
            name="CustomerLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_user_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="LINE userId"
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เชื่อมเมื่อ"),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line",
                        to="customers.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "ลูกค้า ↔ LINE",
                "verbose_name_plural": "ลูกค้า ↔ LINE",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        default="line", max_length=20, verbose_name="ช่องทาง"
                    ),
                ),
                ("message", models.TextField(verbose_name="ข้อความ")),
                (
                    "status",
                    models.CharField(
                        default="queued", max_length=20, verbose_name="สถานะ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติแจ้งเตือน",
                "verbose_name_plural": "ประวัติแจ้งเตือน",
                "ordering": ["-created_at"],
            },
        ),
    ]
