# Generated by Django 5.1.15 on 2026-07-19 12:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("sell", "ขายออกหน้าร้าน"),
                            ("buy", "ซื้อเข้าหน้าร้าน"),
                            ("sell_ws", "ขายของเก่าให้ร้านส่ง"),
                            ("buy_ws", "ซื้อของใหม่จากร้านส่ง"),
                        ],
                        max_length=10,
                        verbose_name="ชนิดบิล",
                    ),
                ),
                (
                    "doc_no",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="เลขที่เอกสาร"
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="เวลา")),
                (
                    "gold_price_ref",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="ราคาทองอ้างอิง",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="ยอดรวม",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="ภาษีมูลค่าเพิ่ม",
                    ),
                ),
                (
                    "full_tax_invoice",
                    models.BooleanField(
                        default=False, verbose_name="ใบกำกับภาษีเต็มรูปแบบ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้บันทึก",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="customers.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "บิล (ซื้อ/ขาย)",
                "verbose_name_plural": "บิล (ซื้อ/ขาย)",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BillDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purity_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("96.5"),
                        max_digits=5,
                        verbose_name="% เนื้อโลหะ",
                    ),
                ),
                (
                    "weight_gram",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="น้ำหนัก (กรัม)"
                    ),
                ),
                (
                    "price_per_gram",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="ราคาต่อกรัม",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="ค่ากำเหน็จ",
                    ),
                ),
                (
                    "fee_applied",
                    models.BooleanField(default=False, verbose_name="หักค่าบริการ"),
                ),
                (
                    "fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=4,
                        verbose_name="ค่าบริการ (%)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="ยอดก่อนหัก",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="ยอดสุทธิ",
                    ),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="ต้นทุน",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="กำไร",
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.metaltype",
                        verbose_name="ประเภทโลหะ",
                    ),
                ),
                (
                    "product_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.productitem",
                        verbose_name="สินค้า",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="sales.billhead",
                        verbose_name="บิล",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการบิล",
                "verbose_name_plural": "รายการบิล",
            },
        ),
        migrations.CreateModel(
            name="BillItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="items/%Y/%m/", verbose_name="รูปชิ้นงาน"
                    ),
                ),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="sales.billdetail",
                        verbose_name="รายการ",
                    ),
                ),
            ],
            options={
                "verbose_name": "รูปชิ้นงาน",
                "verbose_name_plural": "รูปชิ้นงาน",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "เงินสด"),
                            ("transfer", "เงินโอน"),
                            ("aeon", "อิออน"),
                            ("firstchoice", "เฟิร์สช้อยส์"),
                            ("credit", "บัตรเครดิต"),
                        ],
                        default="cash",
                        max_length=15,
                        verbose_name="วิธีชำระ",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="จำนวนเงิน",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="ค่าธรรมเนียม",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales.billhead",
                        verbose_name="บิล",
                    ),
                ),
            ],
            options={
                "verbose_name": "การชำระเงิน",
                "verbose_name_plural": "การชำระเงิน",
            },
        ),
    ]
