# Generated by Django 5.1.15 on 2026-07-19 13:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_supplier_vatsetting_metaltype_vat_exempt_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billdetail",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="VAT",
            ),
        ),
        migrations.AddField(
            model_name="billdetail",
            name="vat_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="ฐานภาษี (ส่วนต่าง)",
            ),
        ),
        migrations.AddField(
            model_name="billhead",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="ใช้เมื่อเป็นธุรกรรมค้าส่ง (sell_ws/buy_ws)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="catalog.supplier",
                verbose_name="ร้านส่ง/คู่ค้า",
            ),
        ),
    ]
